// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListApp.Api.Migrations
{
    [DbContext(typeof(CarListDbContext))]
    [Migration("20241205145608_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Honda",
                            Model = "Fit",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Toyota",
                            Model = "Prado",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Honda",
                            Model = "Civic",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 4,
                            Make = "Audi",
                            Model = "A5",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 5,
                            Make = "BMW",
                            Model = "M3",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 6,
                            Make = "Nissan",
                            Model = "Note",
                            Vin = "123"
                        },
                        new
                        {
                            Id = 7,
                            Make = "Ferrari",
                            Model = "Spider",
                            Vin = "123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
